gallery-dl:: json-tools # mangadex-covers script uses jq
	$(PRINT)
	sudo curl -fsSL https://github.com/mikf/gallery-dl/releases/latest/download/gallery-dl.bin \
		-o /usr/local/bin/gallery-dl
	sudo chmod +x /usr/local/bin/gallery-dl
