#!/bin/bash
set -eo pipefail

# https://gist.github.com/maxkagamine/7e3741b883a272230eb451bdd84a8e23
wget http://ftp.gnu.org/gnu/stow/stow-latest.tar.gz -O - | tar -xzC /tmp
( cd /tmp/stow* && ./configure && make install )
rm -rf /tmp/stow*

mkdir -p ~/.local/bin
mkdir -p /usr/share/doc/fzf/examples

wget "https://raw.githubusercontent.com/junegunn/fzf/$(fzf --version)/shell/key-bindings.bash" \
  -O /usr/share/doc/fzf/examples/key-bindings.bash

sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- \
  -y -b ~/.local/bin >/dev/null

stow -R \
  bash \
  dircolors \
  empty_string_is_git_status \
  fzf \
  git \
  nano \
  starship \
  unraid
