#!/bin/bash
set -eo pipefail

#region Passwordless sudo
sudo EDITOR=tee visudo -f /etc/sudoers.d/wsl >/dev/null <<EOF
Defaults  !env_reset
Defaults  !secure_path
%sudo     ALL=(ALL) NOPASSWD:ALL
EOF
#endregion

#region Network drive mount
if [[ ! -d /mnt/s ]]; then
  echo 'S: /mnt/s drvfs uid=1000,gid=1000,umask=022,fmask=111 0 0' | \
    sudo tee -a /etc/fstab >/dev/null && sudo mkdir /mnt/s && sudo mount -a
fi
#endregion

curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -

sudo apt-get install -qy \
  bat \
  build-essential \
  fd-find \
  ffmpeg \
  fzf \
  gifsicle \
  imagemagick \
  jq \
  libimage-exiftool-perl \
  mediainfo \
  nodejs \
  p7zip-rar \
  protobuf-compiler \
  python-is-python3 \
  python3-pip \
  shellcheck \
  stow \
  tree \
  unzip

mkdir -p ~/.local/bin

ln -fs /usr/bin/batcat ~/.local/bin/bat
ln -fs /usr/bin/fdfind ~/.local/bin/fd

wget https://github.com/BlackReloaded/wsl2-ssh-pageant/releases/latest/download/wsl2-ssh-pageant.exe \
  -O ~/.local/bin/wsl2-ssh-pageant.exe; chmod +x "$_"

wget https://yt-dl.org/downloads/latest/youtube-dl \
  -O ~/.local/bin/youtube-dl; chmod +x "$_"

curl -fsSL https://starship.rs/install.sh | sh -s -- \
  -y -b ~/.local/bin >/dev/null

curl -fsSL https://api.github.com/repos/ImageOptim/gifski/releases/latest | \
  grep -Po '(?<="browser_download_url": ").*amd64.deb' | \
  wget -i - -O /tmp/gifski.deb
sudo apt install /tmp/gifski.deb
rm /tmp/gifski.deb

stow -R \
  bash \
  bat \
  dircolors \
  docker \
  fzf \
  git \
  nano \
  node \
  starship \
  wsl \
  youtube_dl
