#!/bin/bash
set -e

#region Passwordless sudo
sudo EDITOR=tee visudo -f /etc/sudoers.d/wsl >/dev/null <<EOF
Defaults  !env_reset
Defaults  !secure_path
%sudo     ALL=(ALL) NOPASSWD:ALL
EOF
#endregion

#region Windows filesystem mount
sudo tee /etc/wsl.conf >/dev/null <<EOF
[automount]
options = "metadata,umask=022,fmask=111"
EOF

if [[ ! -d /mnt/s ]]; then
  echo 'S: /mnt/s drvfs uid=1000,gid=1000,umask=022,fmask=111 0 0' | \
    sudo tee -a /etc/fstab >/dev/null && sudo mkdir /mnt/s && sudo mount -a
fi
#endregion

curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -

sudo apt-get update && sudo apt-get install -qy \
  stow \
  build-essential \
  fd-find \
  ffmpeg \
  fzf \
  imagemagick \
  jq \
  libimage-exiftool-perl \
  nodejs \
  python-is-python3 \
  shellcheck \
  source-highlight \
  stow \
  tree

mkdir -p ~/.local/bin

wget https://github.com/BlackReloaded/wsl2-ssh-pageant/releases/latest/download/wsl2-ssh-pageant.exe \
  -O ~/.local/bin/wsl2-ssh-pageant.exe && chmod +x "$_"

wget https://yt-dl.org/downloads/latest/youtube-dl \
  -O ~/.local/bin/youtube-dl && chmod +x "$_"

sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- \
  -y -b ~/.local/bin >/dev/null

stow -R \
  bash \
  empty_string_is_git_status \
  fzf \
  git \
  nano \
  node \
  starship \
  wsl \
  youtube_dl
