#!/bin/bash
set -e

sudo tee /etc/wsl.conf >/dev/null <<EOF
[automount]
options = "metadata,umask=022,fmask=111"
EOF

if [[ ! -d /mnt/s ]]; then
  sudo tee -a /etc/fstab >/dev/null <<EOF
S: /mnt/s drvfs metadata,umask=022,fmask=111 0 0
EOF
  sudo mkdir /mnt/s
  sudo mount -a
fi

sudo apt-get update && sudo apt-get install -qy \
  stow \
  fzf \
  jq

wget https://github.com/BlackReloaded/wsl2-ssh-pageant/releases/latest/download/wsl2-ssh-pageant.exe \
  -O ~/.ssh/wsl2-ssh-pageant.exe && chmod +x "$_"

stow -R \
  bash \
  git \
  wsl
