#!/usr/bin/env bash
set -eo pipefail

justsigned=

# shellcheck disable=SC2145
show() { git -c log.showSignature=false show -s --format="$@"; }

if [[ $(show '%G?') == 'N' && $(git config user.signingKey) ]]; then # Not signed and gpg key available

	self=$(printf '%s <%s>\n' "$(git config user.name)" "$(git config user.email)")
	author=$(show '%an <%ae>')
	committer=$(show '%cn <%ce>')

	if [[ $author == "$self" && $committer == "$self" ]]; then
		git commit -q --amend --no-edit --no-verify --only --allow-empty --gpg-sign
		justsigned=1

		echo "🔑  Signed commit, now $(git rev-parse --short HEAD)"
	fi

fi

# Increase stat unless just signed (to avoid double leveling with the amend)
# or rebasing (to avoid power leveling: https://stackoverflow.com/a/3921928)

if [[ ! $justsigned && \
      ! -d $(git rev-parse --git-path rebase-merge) && \
      ! -d $(git rev-parse --git-path rebase-apply) ]]; then

	sweetroll --stat Committing

fi
