[directory]
truncation_length = 4

[directory.substitutions]
"/mnt/c/Users/max/" = "~/"
"/mnt/s/" = "~/"

[hostname]
style = "bold yellow"

[nodejs]
disabled = true

[localip]
disabled = true

[gcloud]
disabled = true
