clef::
	$(PRINT)
	curl -fsSL https://github.com/datalust/clef-tool/releases/download/v2.0.64/clef-2.0.64-linux-x64.tar.gz | \
		tar xfz - --strip-components=1 -C ~/.local/bin clef-2.0.64-linux-x64/clef
	sudo apt-get install -qy expect
